package de.zib.gndms.GORFX.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface GORFXI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * Create an empty offer request for the specified type
   *
   * @param offerRequestArguments
   * @param context
   * @throws UnsupportedOfferType
   *	
   */
  public org.apache.axis.message.addressing.EndpointReferenceType createOfferRequest(types.DynamicOfferDataSeqT offerRequestArguments,types.ContextT context) throws RemoteException, de.zib.gndms.GORFX.stubs.types.UnsupportedOfferType ;

  /**
   * Returns list of supported OfferType URIs
   *
   * @param context
   */
  public org.apache.axis.types.URI[] getSupportedOfferTypes(types.ContextT context) throws RemoteException ;

  /**
   * Run maintenance actions
   *
   * @param action
   * @param options
   */
  public java.lang.Object callMaintenanceAction(java.lang.String action,types.ContextT options) throws RemoteException ;

}

