package de.zib.gndms.GORFX.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface GORFXI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * Create an empty offer request for the specified type
   *
   * @param offerTypeUri
   * @throws UnsupportedOfferType
   *	
   */
  public org.apache.axis.message.addressing.EndpointReferenceType createOfferRequest(org.apache.axis.types.URI offerTypeUri) throws RemoteException, de.zib.gndms.GORFX.stubs.types.UnsupportedOfferType ;

  /**
   * Returns list of supported OfferType URIs
   *
   */
  public org.apache.axis.types.URI[] getSupportedOfferTypes() throws RemoteException ;

}

