package de.zib.gndms.GORFX.ORQ.service.globus;

import de.zib.gndms.GORFX.ORQ.service.ORQImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the GORFXImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class ORQProviderImpl{
	
	ORQImpl impl;
	
	public ORQProviderImpl() throws RemoteException {
		impl = new ORQImpl();
	}
	

    public de.zib.gndms.GORFX.ORQ.stubs.GetOfferAndDestroyRequestResponse getOfferAndDestroyRequest(de.zib.gndms.GORFX.ORQ.stubs.GetOfferAndDestroyRequestRequest params) throws RemoteException, de.zib.gndms.GORFX.ORQ.stubs.types.UnfullfillableRequest {
    de.zib.gndms.GORFX.ORQ.stubs.GetOfferAndDestroyRequestResponse boxedResult = new de.zib.gndms.GORFX.ORQ.stubs.GetOfferAndDestroyRequestResponse();
    boxedResult.setOfferReference(impl.getOfferAndDestroyRequest(params.getOfferExecutionContract().getOfferExecutionContract()));
    return boxedResult;
  }

}
