# Generated by Buildr 1.4.6, change to your liking
#
require 'buildr/java'
include Java
include Commands


# Version number for this release
VERSION_NUMBER = "0.1.0"
# Group identifier for your projects
GROUP = "adis"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << 'http://www.ibiblio.org/maven2'
repositories.remote << 'http://repo1.maven.org/maven2'
repositories.remote << 'http://repository.codehaus.org'
repositories.remote << 'http://google-gson.googlecode.com/svn/mavenrepo'
repositories.remote << 'http://guiceyfruit.googlecode.com/svn/repo/releases'
repositories.remote << 'http://download.java.net/maven/2'
repositories.remote << 'http://static.appfuse.org/repository'
repositories.remote << 'http://repository.jboss.org/maven2'
repositories.remote << 'http://google-maven-repository.googlecode.com/svn/repository'
repositories.remote << 'http://people.apache.org/repo/m2-incubating-repository'
repositories.remote << 'http://repository.jboss.org/nexus/content/groups/public'
repositories.remote << 'http://repo.marketcetera.org/maven'

SLF4J = transitive('org.slf4j:slf4j-log4j12:jar:1.5.8')
JCMD = transitive('com.beust:jcommander:jar:1.19')

desc "AdvancedDiscoveryService"
define "adis" do
        project.version = VERSION_NUMBER
        project.group = GROUP
        manifest["Implementation-Vendor"] = COPYRIGHT

        compile.with SLF4J, JCMD
        mainClass='de.zib.adis.ABI'

        package(:jar).with :manifest=>manifest.merge('Main-Class'=>mainClass)
        package(:jar).include _('etc/*'), :path => ''
        package(:jar).include _('src/main/java/META-INF/*'), :path => 'META-INF/'

        package(:war).with :manifest=>manifest.merge('Main-Class'=>mainClass)
        package(:war).include _('etc/*'), :path => 'WEB-INF/classes/'

        desc "Test runs"
        task 'test1' do
                jars = compile.dependencies.map(&:to_s)
                jars += [project.package(:jar).to_s]
                args = ['--baseurl', 'localhost:8080/vold/', "getwss"]

                Commands.java(mainClass,
                        args, { :classpath => jars, :verbose => true } )
        end
end

# vim:ft=ruby
