package de.zib.gndms.infra.action;

import de.zib.gndms.kit.monitor.ActionCaller;
import org.jetbrains.annotations.NotNull;

import java.io.PrintWriter;

/**
 * A class implementing the WSActionCaller interface must provide a method to created specified ConfigActions
 * and return the result of the ConfigAction's {@code call()} invocation.
 *
 * Note: WSActionCaller is intended to be applicably only for actions implementing the {@code PublicAccess} interface. 
 *
 * @see PublicAccessible
 * @see ActionCaller
 * @author Maik Jorra <jorra@zib.de>
 * @version $Id$
 *          <p/>
 *          User: mjorra, Date: 26.01.2009, Time: 18:28:25
 */
public interface WSActionCaller extends ActionCaller {

    // public actions must implement the PublicAccess interface.

    /**
     * Creates a new ConfigAction object of the specified class {@code className}, sets its options according to
     * {@code opts} (see {@link de.zib.gndms.logic.model.config.ConfigAction#parseLocalOptions(String)})
     * and returns the result of the action's {@code call()} invokation.
     * All outputs are written to the PrintWriter. The postponed actions of the created action must
     * also be invoked.
     *
     * Note: the specified ConfigAction must implement the {@link PublicAccessible} interface.
     *
     * @param className the classname of the ConfigAction which shall be created
     * @param opts A String containing the configuration for the ConfigAction
     * @param writer a printwriter where all output, generated by the ConfigAction, will be written to
     * @return result of the ConfigAction's computation
     * @throws Exception
     */
    Object callPublicAction(final @NotNull String className, final @NotNull String opts,
                            final @NotNull PrintWriter writer) throws Exception;

}
