//
/*
 * Copyright 2008-2010 Zuse Institut Berlin (ZIB)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.11 at 02:32:25 PM CET 
//


package de.zib.gndms.c3resource.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.zib.gndms.c3resource.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _C3GridResource_QNAME = new QName("http://c3grid.de/language/resouces/2007-05-16-resources.xsd", "C3GridResource");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.zib.gndms.c3resource.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Workspace.HttpExport }
     * 
     */
    public Workspace.HttpExport createWorkspaceHttpExport() {
        return new Workspace.HttpExport();
    }

    /**
     * Create an instance of {@link Workspace }
     * 
     */
    public Workspace createWorkspace() {
        return new Workspace();
    }

    /**
     * Create an instance of {@link Metadata.Set }
     * 
     */
    public Metadata.Set createMetadataSet() {
        return new Metadata.Set();
    }

    /**
     * Create an instance of {@link Modules }
     * 
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link C3GridResource }
     * 
     */
    public C3GridResource createC3GridResource() {
        return new C3GridResource();
    }

    /**
     * Create an instance of {@link Workspace.Execution }
     * 
     */
    public Workspace.Execution createWorkspaceExecution() {
        return new Workspace.Execution();
    }

    /**
     * Create an instance of {@link WsGramUrlType }
     * 
     */
    public WsGramUrlType createWsGramUrlType() {
        return new WsGramUrlType();
    }

    /**
     * Create an instance of {@link Modules.Module }
     * 
     */
    public Modules.Module createModulesModule() {
        return new Modules.Module();
    }

    /**
     * Create an instance of {@link Workspace.Archive }
     * 
     */
    public Workspace.Archive createWorkspaceArchive() {
        return new Workspace.Archive();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link C3GridResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd", name = "C3GridResource")
    public JAXBElement<C3GridResource> createC3GridResource(C3GridResource value) {
        return new JAXBElement<C3GridResource>(_C3GridResource_QNAME, C3GridResource.class, null, value);
    }

}
