//
/*
 * Copyright 2008-2010 Zuse Institut Berlin (ZIB)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.11 at 02:32:25 PM CET 
//


package de.zib.gndms.c3resource.jaxb;

import org.apache.cxf.jaxb.JAXBToStringBuilder;
import org.apache.cxf.jaxb.JAXBToStringStyle;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 *         Description of a C3-Grid workspace. This workspace MUST conform
 *         to the specification of
 *         http://www.c3grid.de/fileadmin/c3outreach/generation-0/Konfiguration_Workspace_deliverable.pdf
 *       
 * 
 * <p>Java class for workspace complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workspace">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="execution" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="wsGramUrl" type="{http://c3grid.de/language/resouces/2007-05-16-resources.xsd}wsGramUrlType"/>
 *                   &lt;/choice>
 *                   &lt;element name="modules" type="{http://c3grid.de/language/resouces/2007-05-16-resources.xsd}modules"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="archive" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="oidPrefix" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="baseWorkflow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="httpExport" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="httpUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="gsiftpUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workspace", namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd", propOrder = {
    "baseUrl",
    "execution",
    "archive",
    "httpExport",
    "any"
})
public class Workspace {

    @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String baseUrl;
    @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd")
    protected List<Workspace.Execution> execution;
    @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd")
    protected List<Workspace.Archive> archive;
    @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd")
    protected Workspace.HttpExport httpExport;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the baseUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * Sets the value of the baseUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseUrl(String value) {
        this.baseUrl = value;
    }

    /**
     * Gets the value of the execution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the execution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExecution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Workspace.Execution }
     * 
     * 
     */
    public List<Workspace.Execution> getExecution() {
        if (execution == null) {
            execution = new ArrayList<Workspace.Execution>();
        }
        return this.execution;
    }

    /**
     * Gets the value of the archive property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the archive property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchive().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Workspace.Archive }
     * 
     * 
     */
    public List<Workspace.Archive> getArchive() {
        if (archive == null) {
            archive = new ArrayList<Workspace.Archive>();
        }
        return this.archive;
    }

    /**
     * Gets the value of the httpExport property.
     * 
     * @return
     *     possible object is
     *     {@link Workspace.HttpExport }
     *     
     */
    public Workspace.HttpExport getHttpExport() {
        return httpExport;
    }

    /**
     * Sets the value of the httpExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Workspace.HttpExport }
     *     
     */
    public void setHttpExport(Workspace.HttpExport value) {
        this.httpExport = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return JAXBToStringBuilder.valueOf(this, JAXBToStringStyle.MULTI_LINE_STYLE);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="oidPrefix" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="baseWorkflow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "baseUrl",
        "oidPrefix",
        "baseWorkflow"
    })
    public static class Archive {

        @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String baseUrl;
        @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd")
        protected List<String> oidPrefix;
        @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd")
        protected String baseWorkflow;

        /**
         * Gets the value of the baseUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBaseUrl() {
            return baseUrl;
        }

        /**
         * Sets the value of the baseUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBaseUrl(String value) {
            this.baseUrl = value;
        }

        /**
         * Gets the value of the oidPrefix property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the oidPrefix property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOidPrefix().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOidPrefix() {
            if (oidPrefix == null) {
                oidPrefix = new ArrayList<String>();
            }
            return this.oidPrefix;
        }

        /**
         * Gets the value of the baseWorkflow property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBaseWorkflow() {
            return baseWorkflow;
        }

        /**
         * Sets the value of the baseWorkflow property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBaseWorkflow(String value) {
            this.baseWorkflow = value;
        }

        /**
         * Generates a String representation of the contents of this type.
         * This is an extension method, produced by the 'ts' xjc plugin
         * 
         */
        @Override
        public String toString() {
            return JAXBToStringBuilder.valueOf(this, JAXBToStringStyle.MULTI_LINE_STYLE);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="wsGramUrl" type="{http://c3grid.de/language/resouces/2007-05-16-resources.xsd}wsGramUrlType"/>
     *         &lt;/choice>
     *         &lt;element name="modules" type="{http://c3grid.de/language/resouces/2007-05-16-resources.xsd}modules"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "wsGramUrl",
        "modules"
    })
    public static class Execution {

        @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd")
        protected WsGramUrlType wsGramUrl;
        @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd", required = true)
        protected Modules modules;

        /**
         * Gets the value of the wsGramUrl property.
         * 
         * @return
         *     possible object is
         *     {@link WsGramUrlType }
         *     
         */
        public WsGramUrlType getWsGramUrl() {
            return wsGramUrl;
        }

        /**
         * Sets the value of the wsGramUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link WsGramUrlType }
         *     
         */
        public void setWsGramUrl(WsGramUrlType value) {
            this.wsGramUrl = value;
        }

        /**
         * Gets the value of the modules property.
         * 
         * @return
         *     possible object is
         *     {@link Modules }
         *     
         */
        public Modules getModules() {
            return modules;
        }

        /**
         * Sets the value of the modules property.
         * 
         * @param value
         *     allowed object is
         *     {@link Modules }
         *     
         */
        public void setModules(Modules value) {
            this.modules = value;
        }

        /**
         * Generates a String representation of the contents of this type.
         * This is an extension method, produced by the 'ts' xjc plugin
         * 
         */
        @Override
        public String toString() {
            return JAXBToStringBuilder.valueOf(this, JAXBToStringStyle.MULTI_LINE_STYLE);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="httpUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="gsiftpUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "httpUrl",
        "gsiftpUrl"
    })
    public static class HttpExport {

        @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String httpUrl;
        @XmlElement(namespace = "http://c3grid.de/language/resouces/2007-05-16-resources.xsd", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String gsiftpUrl;

        /**
         * Gets the value of the httpUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHttpUrl() {
            return httpUrl;
        }

        /**
         * Sets the value of the httpUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHttpUrl(String value) {
            this.httpUrl = value;
        }

        /**
         * Gets the value of the gsiftpUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGsiftpUrl() {
            return gsiftpUrl;
        }

        /**
         * Sets the value of the gsiftpUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGsiftpUrl(String value) {
            this.gsiftpUrl = value;
        }

        /**
         * Generates a String representation of the contents of this type.
         * This is an extension method, produced by the 'ts' xjc plugin
         * 
         */
        @Override
        public String toString() {
            return JAXBToStringBuilder.valueOf(this, JAXBToStringStyle.MULTI_LINE_STYLE);
        }

    }

}
