package de.zib.gndms.dspace.slice.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class SliceImpl extends SliceImplBase {

	
	public SliceImpl() throws RemoteException {
		super();
	}
	
  public de.zib.gndms.dspace.slice.stubs.types.SliceReference transformSlice(javax.xml.namespace.QName sliceKind) throws RemoteException, de.zib.gndms.dspace.subspace.stubs.types.UnknownOrInvalidSliceKind {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public de.zib.gndms.dspace.slice.stubs.types.SliceReference transformSliceTo(javax.xml.namespace.QName subspaceSpecifier,javax.xml.namespace.QName sliceKind) throws RemoteException, de.zib.gndms.dspace.stubs.types.UnknownSubspace, de.zib.gndms.dspace.subspace.stubs.types.OutOfSpace, de.zib.gndms.dspace.subspace.stubs.types.UnknownOrInvalidSliceKind {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

