package de.zib.gndms.dspace.slice.service;

import de.zib.gndms.dspace.slice.stubs.types.SliceReference;
import de.zib.gndms.dspace.slice.service.globus.resource.SliceResource;
import de.zib.gndms.dspace.slice.service.globus.resource.ExtSliceResourceHome;
import de.zib.gndms.dspace.stubs.types.UnknownSubspace;
import de.zib.gndms.dspace.stubs.types.InternalFailure;
import de.zib.gndms.dspace.subspace.stubs.types.OutOfSpace;
import de.zib.gndms.dspace.subspace.stubs.types.UnknownOrInvalidSliceKind;
import de.zib.gndms.model.dspace.Slice;

import javax.persistence.EntityManager;
import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class SliceImpl extends SliceImplBase {

	
	public SliceImpl() throws RemoteException {
		super();
	}
	

  public de.zib.gndms.dspace.slice.stubs.types.SliceReference transformSliceTo(types.SliceTransformSpecifierT sliceTransformSpecifier,types.ContextT context) throws RemoteException, UnknownSubspace, OutOfSpace, UnknownOrInvalidSliceKind, InternalFailure {

      ExtSliceResourceHome esr;
      SliceResource sr;
      try {
          esr = (ExtSliceResourceHome) getResourceHome(  );
          sr = esr.getAddressedResource();
      } catch ( Exception e ) {
          throw new RemoteException( "Can't obtain slice resource home." );
      }

      EntityManager em = esr.getSystem().getEntityManagerFactory().createEntityManager(  );

//      Slice osl = em.find( )

      // check which attribute shall be transformed.
      if( sliceTransformSpecifier.getSubspaceSpecifier() != null )
      
      //TODO: Implement this autogenerated method
      throw new RemoteException("Not yet implemented");

      return null;
  }

}

