package de.zib.gndms.dspace.subspace.service;

import de.zib.gndms.dspace.slice.stubs.types.SliceReference;
import de.zib.gndms.dspace.subspace.stubs.types.OutOfSpace;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class SubspaceImpl extends SubspaceImplBase {

	
	public SubspaceImpl() throws RemoteException {
		super();
	}
	
  public SliceReference createSlice(types.SliceCreationSpecifier sliceCreationSpecifier,types.ContextT context) throws RemoteException, OutOfSpace, de.zib.gndms.dspace.subspace.stubs.types.UnknownOrInvalidSliceKind, de.zib.gndms.dspace.stubs.types.InternalFailure {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public javax.xml.namespace.QName[] listCreatableSliceKinds() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

