package de.zib.gndms.GORFX.offer.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class OfferImpl extends OfferImplBase {

	
	public OfferImpl() throws RemoteException {
		super();
	}
	
  public org.apache.axis.message.addressing.EndpointReferenceType accept() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

