package de.zib.gndms.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class WHORFXImpl extends WHORFXImplBase {

	
	public WHORFXImpl() throws RemoteException {
		super();
	}
	
  public org.apache.axis.types.URI lookupORF(org.apache.axis.types.URI orfType) throws RemoteException, de.zib.gndms.stubs.types.UnknownORFType {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

