package de.zib.gndms.lofis.lofiset.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import de.zib.gndms.lofis.lofiset.stubs.LofiSetPortType;
import de.zib.gndms.lofis.lofiset.stubs.service.LofiSetServiceAddressingLocator;
import de.zib.gndms.lofis.lofiset.common.LofiSetI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.2
 */
public class LofiSetClient extends LofiSetClientBase implements LofiSetI {	

	public LofiSetClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public LofiSetClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public LofiSetClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public LofiSetClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(LofiSetClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  LofiSetClient client = new LofiSetClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"destroy");
    return portType.destroy(params);
    }
  }

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"setTerminationTime");
    return portType.setTerminationTime(params);
    }
  }

  public org.oasis.wsn.SubscribeResponse subscribe(org.oasis.wsn.Subscribe params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"subscribe");
    return portType.subscribe(params);
    }
  }

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

  public types.ReplicaSliceT[] getAvailableReplicaSlices(boolean completeSlicesOnly) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getAvailableReplicaSlices");
    de.zib.gndms.lofis.lofiset.stubs.GetAvailableReplicaSlicesRequest params = new de.zib.gndms.lofis.lofiset.stubs.GetAvailableReplicaSlicesRequest();
    params.setCompleteSlicesOnly(completeSlicesOnly);
    de.zib.gndms.lofis.lofiset.stubs.GetAvailableReplicaSlicesResponse boxedResult = portType.getAvailableReplicaSlices(params);
    return boxedResult.getReplicaSlice();
    }
  }

  public de.zib.gndms.lofis.lofiset.client.LofiSetClient getSubLofiSet(types.ConflictResolvingFileMappingSeqT lofiMap) throws RemoteException, org.apache.axis.types.URI.MalformedURIException, de.zib.gndms.lofis.stubs.types.MissingSourceFiles, de.zib.gndms.lofis.stubs.types.ConflictingDestinationsInMap {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getSubLofiSet");
    de.zib.gndms.lofis.lofiset.stubs.GetSubLofiSetRequest params = new de.zib.gndms.lofis.lofiset.stubs.GetSubLofiSetRequest();
    de.zib.gndms.lofis.lofiset.stubs.GetSubLofiSetRequestLofiMap lofiMapContainer = new de.zib.gndms.lofis.lofiset.stubs.GetSubLofiSetRequestLofiMap();
    lofiMapContainer.setLofiMap(lofiMap);
    params.setLofiMap(lofiMapContainer);
    de.zib.gndms.lofis.lofiset.stubs.GetSubLofiSetResponse boxedResult = portType.getSubLofiSet(params);
    EndpointReferenceType ref = boxedResult.getLofiSetReference().getEndpointReference();
    return new de.zib.gndms.lofis.lofiset.client.LofiSetClient(ref);
    }
  }

}
