package de.zib.gndms.lofis.service;

import de.zib.gndms.lofis.service.globus.resource.LOFISResource;
import  de.zib.gndms.lofis.service.LOFISConfiguration;

import java.rmi.RemoteException;

import javax.naming.InitialContext;
import javax.xml.namespace.QName;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;
import org.globus.wsrf.ResourceContext;
import org.globus.wsrf.ResourceContextException;
import org.globus.wsrf.ResourceException;
import org.globus.wsrf.ResourceHome;
import org.globus.wsrf.ResourceProperty;
import org.globus.wsrf.ResourcePropertySet;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * Provides some simple accessors for the Impl.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public abstract class LOFISImplBase {
	
	public LOFISImplBase() throws RemoteException {
	
	}
	
	public LOFISConfiguration getConfiguration() throws Exception {
		return LOFISConfiguration.getConfiguration();
	}
	
	
	public de.zib.gndms.lofis.service.globus.resource.LOFISResourceHome getResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("home");
		return (de.zib.gndms.lofis.service.globus.resource.LOFISResourceHome)resource;
	}

	
	
	
	public de.zib.gndms.lofis.lofiset.service.globus.resource.LofiSetResourceHome getLofiSetResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("lofiSetHome");
		return (de.zib.gndms.lofis.lofiset.service.globus.resource.LofiSetResourceHome)resource;
	}
	
	
	protected ResourceHome getResourceHome(String resourceKey) throws Exception {
		MessageContext ctx = MessageContext.getCurrentContext();

		ResourceHome resourceHome = null;
		
		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/" + resourceKey;
		try {
			javax.naming.Context initialContext = new InitialContext();
			resourceHome = (ResourceHome) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate resource home. : " + resourceKey, e);
		}

		return resourceHome;
	}


}

