package de.zib.gndms.GORFX.context.service.globus.resource;

import de.zib.gndms.GORFX.service.globus.resource.ExtGORFXResourceHome;
import de.zib.gndms.infra.GNDMSTools;
import de.zib.gndms.infra.GridConfig;
import de.zib.gndms.infra.service.GNDMPersistentServiceHome;
import de.zib.gndms.infra.system.GNDMSystem;
import de.zib.gndms.model.gorfx.Task;
import org.apache.axis.message.addressing.AttributedURI;
import org.apache.axis.types.URI;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.globus.wsrf.ResourceException;
import org.globus.wsrf.ResourceKey;
import org.globus.wsrf.Resource;
import org.globus.wsrf.impl.SimpleResourceKey;
import org.jetbrains.annotations.NotNull;

import javax.naming.NamingException;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;

/**
 * This class overrides the ResourceHome that is automatically generated by introduce for Globus
 * Toolkit. In GNDMS this is mainly necessary to provide RDBMS/JPA-based resource persistence.
 * In order to use the extended resource home they have to be configured in jndi-config.xml.
 * If this has been done properly, you should see an info-level log message during the start up
 * of the web service container that notifies succesfull initialization of the extended resource
 * home.
 *
 * @author Stefan Plantikow <plantikow@zib.de>
 * @version $Id$
 *
 *          User: stepn Date: 16.07.2008 Time: 12:35:27
 */
public final class ExtTaskResourceHome extends TaskResourceHome implements GNDMPersistentServiceHome<Task> {

	// logger can be an instance field since resource home classes are instantiated at most once
	@NotNull
	@SuppressWarnings({"FieldNameHidesFieldInSuperclass"})
	private final Log logger = LogFactory.getLog(ExtTaskResourceHome.class);

    @NotNull
    private GNDMSystem system;

    @NotNull
    private AttributedURI serviceAddress;

    private boolean initialized = false;

    @Override
	public synchronized void initialize() throws Exception {
        if (! initialized) {
			logger.info("Extended Task home initializing");
			try { try {
                final GridConfig gridConfig = ExtGORFXResourceHome.getGridConfig();
                logger.debug("Config: " + gridConfig.asString());
                system = gridConfig.retrieveSystemReference();
				serviceAddress = GNDMSTools.getServiceAddressFromContext();

				initialized = true;

				super.initialize();    // Overridden method
			}
			catch ( NamingException e) {
				throw new RuntimeException(e);
			} }
            catch (RuntimeException e) {
                initialized = false;
                logger.error("Initialization failed", e);
                e.printStackTrace(System.err);
                throw e;
            }
		}
	}

	private void ensureInitialized() {
		try
			{ initialize();	}
		catch (Exception e) {
			logger.error("Unexpected initialization error", e);
			throw new RuntimeException(e);
		}
	}


    @NotNull
    public Query getListAllQuery( @NotNull EntityManager em ) {
        return em.createNamedQuery( "listAllTaskIds" );
    }


    public void refresh( @NotNull Task resourceModel ) throws ResourceException {

        ResourceKey key = getKeyForResourceModel( resourceModel );
        TaskResource  tres = (TaskResource) find( key );

        tres.loadFromModel( resourceModel );
    }


    @NotNull
    public String getNickName() {
        return "task";
    }


    @NotNull
    public Class<Task> getModelClass() {
        return Task.class;
    }


    public ResourceKey getKeyForResourceModel(@NotNull final Task model) {
        return getKeyForId(model.getId());
    }


    public ResourceKey getKeyForId( @NotNull String id ) {
        return new SimpleResourceKey( getKeyTypeName( ), id );
    }


    @NotNull
    public URI getServiceAddress() {
        ensureInitialized();
        return serviceAddress;
    }


    @NotNull
    public EntityManagerFactory getEntityManagerFactory() {
        return getSystem().getEntityManagerFactory();
    }


    @NotNull
    public GNDMSystem getSystem() throws IllegalStateException {
        ensureInitialized();
        return system;
    }


    public void setSystem( @NotNull GNDMSystem system ) throws IllegalStateException {
        throw new UnsupportedOperationException( "System is read-only" );
    }


    @Override
    protected Resource createNewInstance() throws ResourceException {
        final Resource resource = super.createNewInstance();
        ((TaskResource)resource).setResourceHome(this);
        return resource;    // Overridden method
    }


    public Log getLog() {
        return logger;
    }
}
