require "#{ENV['GNDMS_REST']}/buildr/gndms_modules"
include GNDMS_MODULES

PLUGIN_VERSION_NUMBER = '0.6.0-pre'
PLUGIN_NAME = "interSliceTransfer"
# Don't touch below unless you know what you are doing
# --------------------------------------------------------------------------------------------------


setupGNDMSModules()
setupModules( "../fileTransfer", "fileTransfer" )

# test if vars ver constructed properly
puts Module.constants.grep  /GNDMS/ 
puts Module.constants.grep  /FILETR/ 

desc "Plug-in for the #{PLUGIN_NAME} task-flow"
define PLUGIN_NAME do
    project.version = PLUGIN_VERSION_NUMBER
    manifest['Copyright'] = MF_COPYRIGHT
    manifest['License'] = MF_LICENSE
    compile.options.source = SOURCE
    compile.options.target = TARGET


    desc 'The client side of the plugin'
    define 'client', :layout => dmsLayout('client',  "#{PLUGIN_NAME}-client") do
      compile.with GOOGLE_COLLECTIONS, COMMONS_FILEUPLOAD, COMMONS_CODEC, GNDMS_COMMON, JETBRAINS_ANNOTATIONS, JODA_TIME, ARGS4J, INJECT, GUICE, GT4_SERVLET, COMMONS_LANG, OPENJPA, SLF4J, JSON, SPRING
      compile
      package :jar
    end


    desc 'The server side of the plugin'
    define 'server', :layout => dmsLayout('server', "#{PLUGIN_NAME}-server") do
      compile.with project('client'), GOOGLE_COLLECTIONS, COMMONS_FILEUPLOAD, COMMONS_CODEC, GNDMS_COMMON, GNDMS_STUFF, GNDMS_MODEL, GNDMS_NEOMODEL, JETBRAINS_ANNOTATIONS, GT4_LOG, GT4_COG, GT4_AXIS, GT4_SEC, GT4_XML, JODA_TIME, ARGS4J, INJECT, GUICE, GT4_SERVLET, COMMONS_LANG, OPENJPA, SLF4J, JSON, SPRING

      compile
      package :jar
    end
end
