package de.zib.gndms.lofis.lofiset.service.globus;

import de.zib.gndms.lofis.lofiset.service.LofiSetImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the LOFISImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class LofiSetProviderImpl{
	
	LofiSetImpl impl;
	
	public LofiSetProviderImpl() throws RemoteException {
		impl = new LofiSetImpl();
	}
	

    public de.zib.gndms.lofis.lofiset.stubs.GetAvailableReplicaSlicesResponse getAvailableReplicaSlices(de.zib.gndms.lofis.lofiset.stubs.GetAvailableReplicaSlicesRequest params) throws RemoteException {
    de.zib.gndms.lofis.lofiset.stubs.GetAvailableReplicaSlicesResponse boxedResult = new de.zib.gndms.lofis.lofiset.stubs.GetAvailableReplicaSlicesResponse();
    boxedResult.setReplicaSlice(impl.getAvailableReplicaSlices(params.isCompleteSlicesOnly()));
    return boxedResult;
  }

    public de.zib.gndms.lofis.lofiset.stubs.GetSubLofiSetResponse getSubLofiSet(de.zib.gndms.lofis.lofiset.stubs.GetSubLofiSetRequest params) throws RemoteException {
    de.zib.gndms.lofis.lofiset.stubs.GetSubLofiSetResponse boxedResult = new de.zib.gndms.lofis.lofiset.stubs.GetSubLofiSetResponse();
    boxedResult.setLofiSetReference(impl.getSubLofiSet(params.getLofiMap().getLofiMap()));
    return boxedResult;
  }

}
