package de.zib.gndms.dspace.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class DSpaceImpl extends DSpaceImplBase {

	
	public DSpaceImpl() throws RemoteException {
		super();
	}
	

  public de.zib.gndms.dspace.subpace.stubs.types.SubspaceReference[] listPublicSubspaces(org.apache.axis.types.URI schemaURI) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public org.apache.axis.types.URI[] listSupportedSchemas() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public de.zib.gndms.dspace.subpace.stubs.types.SubspaceReference getSubspace(javax.xml.namespace.QName subspaceSpecifier) throws RemoteException, de.zib.gndms.dspace.stubs.types.UnknownSubspace {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

