package de.zib.gndms.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface WHORFXI {

  /**
   * Run maintenance actions
   *
   * @param action
   * @param options
   */
  public java.lang.Object callMaintenanceAction(java.lang.String action,types.ContextT options) throws RemoteException ;

  /**
   * Lookop ORF by Type
   *
   * @param orfType
   * @param context
   * @throws UnknownORFType
   *	
   */
  public org.apache.axis.types.URI lookupORF(org.apache.axis.types.URI orfType,types.ContextT context) throws RemoteException, de.zib.gndms.stubs.types.UnknownORFType ;

  /**
   * Reread ORF Mappings from file.
   *
   */
  public void updateMappings() throws RemoteException ;

}

