package de.zib.gndms.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface WHORFXI {

  /**
   * Lookop ORF by Type
   *
   * @param orfType
   * @throws UnknownORFType
   *	
   */
  public org.apache.axis.types.URI lookupORF(org.apache.axis.types.URI orfType) throws RemoteException, de.zib.gndms.stubs.types.UnknownORFType ;

}

