package de.zib.gndms.GORFX.service;

import de.zib.gndms.GORFX.ORQ.service.globus.resource.ExtORQResourceHome;
import de.zib.gndms.GORFX.ORQ.service.globus.resource.ORQResource;
import de.zib.gndms.GORFX.context.service.globus.resource.ExtTaskResourceHome;
import de.zib.gndms.GORFX.offer.service.globus.resource.ExtOfferResourceHome;
import de.zib.gndms.GORFX.service.globus.resource.ExtGORFXResourceHome;
import de.zib.gndms.infra.system.GNDMSystem;
import de.zib.gndms.infra.system.InstanceDirectory;
import de.zib.gndms.shared.ContextTAux;
import de.zib.gndms.kit.util.WidAux;
import org.apache.log4j.Logger;
import org.globus.wsrf.ResourceKey;
import org.jetbrains.annotations.NotNull;

import java.rmi.RemoteException;


/**
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class GORFXImpl extends GORFXImplBase {

    private static final Logger logger;
    private final GNDMSystem system;


    static {
        logger = Logger.getLogger(GORFXImpl.class);
    }


    @SuppressWarnings({ "FeatureEnvy" })
    public GORFXImpl() throws RemoteException {
        super();
        try {
            final @NotNull ExtGORFXResourceHome home = getResourceHome();
            system = home.getSystem();
            InstanceDirectory instanceDir = system.getInstanceDir();
            instanceDir.addHome(home);
            instanceDir.addHome(getORQResourceHome());
            instanceDir.addHome(getOfferResourceHome());
            instanceDir.addHome(getTaskResourceHome());
        }
        catch (Exception e) {
            e.printStackTrace(System.err);
            throw new RuntimeException(e);
        }
        finally {
            WidAux.removeWid();
        }
    }


    public org.apache.axis.message.addressing.EndpointReferenceType createOfferRequest(types.DynamicOfferDataSeqT offerRequestArguments,types.ContextT context) throws RemoteException, de.zib.gndms.GORFX.stubs.types.UnsupportedOfferType {

        try{
            ContextTAux.initWid(getSystem().getModelUUIDGen(), context);

            @NotNull ExtORQResourceHome home = (ExtORQResourceHome) getORQResourceHome();
            @NotNull ResourceKey key = home.createResource();            
            ORQResource orqr = (ORQResource) home.find( key );
            orqr.setCachedWid(WidAux.getWid());
            orqr.setOfferRequestArguments( offerRequestArguments, context);

            // todo: Do we have to return the epr isn't the resourceRef sufficient.
            return home.getResourceReference( key ).getEndpointReference();
        } catch ( Exception e ) {
            e.printStackTrace();
            throw new RemoteException( e.getMessage(), e );
        }
        finally {
            WidAux.removeWid();
        }
    }


    public org.apache.axis.types.URI[] getSupportedOfferTypes(types.ContextT context) throws RemoteException {

        try{
            ContextTAux.initWid(getSystem().getModelUUIDGen(), context);
            return getResourceHome().getAddressedResource().getSupportedOfferTypes( );
        } catch ( Exception e ) {
            throw new RemoteException(e.getMessage(), e);
        }
        finally {
            WidAux.removeWid();
        }
    }


    public java.lang.Object callMaintenanceAction(java.lang.String action,types.ContextT context) throws RemoteException {
        //TODO: Implement this autogenerated method
        try {
            ContextTAux.initWid(getSystem().getModelUUIDGen(), context);
            throw new RemoteException("Not yet implemented");
        }
        finally {
            WidAux.removeWid();
        }
    }


    @Override
    public ExtGORFXResourceHome getResourceHome() throws Exception {
        return (ExtGORFXResourceHome) super.getResourceHome();    // Overridden method
    }


    @Override
    public ExtORQResourceHome getORQResourceHome() throws Exception {
        return (ExtORQResourceHome) super.getORQResourceHome();    // Overridden method
    }


    @Override
    public ExtOfferResourceHome getOfferResourceHome() throws Exception {
        return (ExtOfferResourceHome) super.getOfferResourceHome();    // Overridden method
    }


    @Override
    public ExtTaskResourceHome getTaskResourceHome() throws Exception {
        return (ExtTaskResourceHome) super.getTaskResourceHome();    // Overridden method
    }


    public @NotNull GNDMSystem getSystem() {
        return system;
    }
}

