package de.zib.gndms.dspace.subpace.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface SubspaceI {

  public org.oasis.wsn.SubscribeResponse subscribe(org.oasis.wsn.Subscribe params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * Creates a new slice with the given kind in this subspace
   *
   * @param sliceKind
   * @param sliceSize
   * @param terminationTime
   * @throws UnsupportedOrInvalidSliceKind
   *	
   * @throws OutOfSpace
   *	
   */
  public de.zib.gndms.dspace.slice.stubs.types.SliceReference createSlice(javax.xml.namespace.QName sliceKind,types.StorageSizeT sliceSize,java.util.Calendar terminationTime) throws RemoteException, de.zib.gndms.dspace.subpace.stubs.types.UnsupportedOrInvalidSliceKind, de.zib.gndms.dspace.subpace.stubs.types.OutOfSpace ;

  /**
   * Returns a (possibly incompletet) list of all slice kinds supported by this subspaces CreateSlice() method
   *
   */
  public javax.xml.namespace.QName[] listCreatableSliceKinds() throws RemoteException ;

}

