require "#{ENV['GNDMS_SOURCE']}/buildr/gndms_modules"
include GNDMS_MODULES

PLUGIN_VERSION_NUMBER = '0.6.4'
# Don't touch below unless you know what you are doing
# --------------------------------------------------------------------------------------------------


setupGNDMSModules()

desc 'Plug-in for the Publishing task-flow'
define 'publishing' do
    project.version = PLUGIN_VERSION_NUMBER
    manifest['Copyright'] = MF_COPYRIGHT
    manifest['License'] = MF_LICENSE
    compile.options.source = SOURCE
    compile.options.target = TARGET


    desc 'The client side of the plugin'
    define 'client', :layout => dmsLayout('client', 'publishing-client') do
      compile.with COMMONS_CODEC, COMMONS_LOGGING, GNDMS_STUFF, GNDMS_COMMON, GNDMS_GNDMC_REST, JETBRAINS_ANNOTATIONS, JODA_TIME, ARGS4J, INJECT, GT4_SERVLET, COMMONS_LANG, SLF4J, JSON, SPRING_CLIENT, XSTREAM, XSTREAM_DEPS
      compile
#      package( :jar ).include _("src/log4j.properties"), :path => "."  
      package :jar

        desc 'Runs the Publishing test client'
        task 'run' do |t|
            jars = compile.dependencies.map(&:to_s)
            jars << compile.target.to_s
            args = [ '-uri', 'http://localhost:8080/gndms/c3grid/' ] 
            props = {}
            runner = 'de.zib.gndms.taskflows.publishing.client.tools.PublishingExample'
            runJava( t.to_s, runner, args, jars, props )
        end
    end


    desc 'The server side of the plugin'
    define 'server', :layout => dmsLayout('server', 'publishing-server') do
        compile.with project('client'), GOOGLE_COLLECTIONS, COMMONS_FILEUPLOAD, COMMONS_CODEC, GNDMS_COMMON, GNDMS_STUFF, GNDMS_MODEL, GNDMS_NEOMODEL, GNDMS_KIT, GNDMS_LOGIC, GNDMS_INFRA, GNDMS_GNDMC_REST, JETBRAINS_ANNOTATIONS, OPENJPA, GT4_LOG, GT4_COG, GT4_SEC, GT4_XML, JODA_TIME, ARGS4J, INJECT, GT4_SERVLET, COMMONS_LANG, OPENJPA, SLF4J, JSON, SPRING, XSTREAM, XSTREAM_DEPS, GNDMS_VOLDMODEL

        compile
        meta_inf << file( _( 'src/META-INF/services' ) )
        meta_inf << file( _( 'src/META-INF/changeIdentifier.xsl' ) )
        package :jar

        desc 'deploys the Publishing server jar'
        task 'deploy' do
            deploy_target = "#{ENV['JETTY_HOME']}/gndms"
            cp project('publishing:server').package(:jar).to_s, deploy_target
            cp project('publishing:client').package(:jar).to_s, deploy_target
        end
    end
end
