package de.zib.gndms.GORFX.ORQ.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class ORQImpl extends ORQImplBase {

	
	public ORQImpl() throws RemoteException {
		super();
	}
	
  public de.zib.gndms.GORFX.offer.stubs.types.OfferReference getOfferAndDestroyRequest(types.OfferExecutionContractT offerExecutionContract) throws RemoteException, de.zib.gndms.GORFX.ORQ.stubs.types.UnfullfillableRequest {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

