package de.zib.gndms.dspace.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import de.zib.gndms.dspace.stubs.DSpacePortType;
import de.zib.gndms.dspace.stubs.service.DSpaceServiceAddressingLocator;
import de.zib.gndms.dspace.common.DSpaceI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.2
 */
public class DSpaceClient extends DSpaceClientBase implements DSpaceI {	

	public DSpaceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public DSpaceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public DSpaceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public DSpaceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(DSpaceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  DSpaceClient client = new DSpaceClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public de.zib.gndms.dspace.subpace.stubs.types.SubspaceReference getSubspaceByName(java.lang.String subspaceName) throws RemoteException, de.zib.gndms.dspace.stubs.types.UnknownSubspace {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getSubspaceByName");
    de.zib.gndms.dspace.stubs.GetSubspaceByNameRequest params = new de.zib.gndms.dspace.stubs.GetSubspaceByNameRequest();
    params.setSubspaceName(subspaceName);
    de.zib.gndms.dspace.stubs.GetSubspaceByNameResponse boxedResult = portType.getSubspaceByName(params);
    return boxedResult.getSubspaceReference();
    }
  }

  public de.zib.gndms.dspace.subpace.stubs.types.SubspaceReference[] listPublicSubspaces() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"listPublicSubspaces");
    de.zib.gndms.dspace.stubs.ListPublicSubspacesRequest params = new de.zib.gndms.dspace.stubs.ListPublicSubspacesRequest();
    de.zib.gndms.dspace.stubs.ListPublicSubspacesResponse boxedResult = portType.listPublicSubspaces(params);
    return boxedResult.getSubspaceReference();
    }
  }

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

}
